### ISSUE TITLE
Prefix = true ends up with error

### ISSUE THREAD

**Issue by VaporFan** [scholtzm/vapor-winston-logger#1]
bot.use(winstonLogger, {
    username: _bot.username,
    consoleLevel: 'debug',
    fileLevel: 'debug',
    logDir: 'logs',
    dateFormat: 'YYYY-MM-DD HH:mm:ss',
    prefix: false
});
C:\xxx\index.js:68
    logger.addFilter(function(msg) {
           ^

---

**Comment by scholtzm** [comment]
What's the actual error message?

Also, you might be running higher version of Winston which changed the way filters are registered. Make sure you are running `^2.1.1`.

**Comment by VaporFan** [comment]
I reinstall winston 2.1.1 but still got error with lastest vapor.

C:\Workspace\Nodejs\vapor\node_modules\vapor-winston-logger\index.js:68
    logger.addFilter(function(msg) {
           ^

TypeError: logger.addFilter is not a function
    at createLogger (C:\Workspace\Nodejs\vapor\node_modules\vapor-winston-logger\index.js:68:12)
    at Object.exports.plugin (C:\Workspace\Nodejs\vapor\node_modules\vapor-winston-logger\index.js:82:16)
    at Vapor.use (C:\Workspace\Nodejs\vapor\node_modules\vapor\lib\vapor.js:140:10)
    at Object.<anonymous> (C:\Workspace\Nodejs\vapor\botserv.js:43:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
 Press any key to continue . . .

**Comment by scholtzm** [comment]
I'll test it out asap.

**edit.** However, your path `C:\Workspace\Nodejs\vapor\node_modules\vapor-winston-logger` looks weird. Logger should not be installed as dependency of vapor.

**Comment by VaporFan** [comment]
Hello,
I just cd in to C:\Workspace\Nodejs\vapor\
And command: npm install vapor-winston-logger
npm WARN vapor-winston-logger@1.0.4 requires a peer of vapor@1.x but none was installed.

Correct me if I'm wrong

**Edit: I**nstalled vapor-winston-logger under vapor/node_modules/vapor-winston-logger. Still doesnt work

**Comment by scholtzm** [comment]
`vapor` itself is a stand-alone library so you should not install anything inside. Instead you should do something like:

``` sh
$ mkdir my-bot; cd my-bot
$ npm i vapor vapor-winston-logger
$ touch my-bot.js # creates empty file

# add code to my-bot.js, e.g. https://github.com/scholtzm/vapor/blob/master/examples/basic/index.js
# in this case change the first line to: var vapor = require('vapor');
# also change username + password and anything else you need

$ node my-bot.js
```

You might want to read up on module system Node.js uses.

**Comment by VaporFan** [comment]
// Add prefix if necessary
  if(config.prefix === true) {
    logger.addFilter(function(msg) {
      return util.format('[%s] %s', username, msg);
    });
  }

This code in vapor-winston just doesnt work

**Comment by VaporFan** [comment]
// Add transports if possible
  if(config.consoleLevel !== 'none') {
    logOptions.transports.push(new (winston.transports.Console)({
      timestamp: function() { return moment().format(config.dateFormat); },
      level: config.consoleLevel,
      label: username, **// This works in Console Log**
      colorize: true
    }));
  }

**Comment by scholtzm** [comment]
Seems like winston.js possibly introduced breaking change while not keeping up with SemVer. Either way, I had finally had some time to push patch release that addresses this issue.

`vapor-winston-logger v1.0.6` contains fix for this problem among other things.
